// Mocks generated by Mockito 5.4.4 from annotations
// in inkapaking/test/core/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i5;
import 'package:inkapaking/core/core.dart' as _i2;
import 'package:inkapaking/features/auth/data/datasources/auth_local_data_source.dart'
    as _i7;
import 'package:inkapaking/features/auth/data/datasources/auth_supabase_data_source.dart'
    as _i6;
import 'package:inkapaking/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i2.Failure, _i2.User>>? signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #signInWithEmailAndPassword,
        [
          email,
          password,
        ],
      )) as _i4.Future<_i5.Either<_i2.Failure, _i2.User>>?);

  @override
  _i4.Future<_i5.Either<_i2.Failure, _i2.User>>? signUpWithDataUser(
    String? name,
    String? lastName,
    bool? gender,
    String? phone,
    String? direction,
    bool? stateAccount,
    String? email,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #signUpWithDataUser,
        [
          name,
          lastName,
          gender,
          phone,
          direction,
          stateAccount,
          email,
        ],
      )) as _i4.Future<_i5.Either<_i2.Failure, _i2.User>>?);

  @override
  _i4.Future<_i5.Either<_i2.Failure, _i2.User>>? getCurrentUser(
          String? email) =>
      (super.noSuchMethod(Invocation.method(
        #getCurrentUser,
        [email],
      )) as _i4.Future<_i5.Either<_i2.Failure, _i2.User>>?);

  @override
  _i4.Future<_i5.Either<_i2.Failure, bool>>? recoverPassword(String? email) =>
      (super.noSuchMethod(Invocation.method(
        #recoverPassword,
        [email],
      )) as _i4.Future<_i5.Either<_i2.Failure, bool>>?);
}

/// A class which mocks [AuthSupabaseDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSupabaseDataSource extends _i1.Mock
    implements _i6.AuthSupabaseDataSource {
  MockAuthSupabaseDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<_i2.UserModel> signUpWithDataUser(
    String? name,
    String? lastName,
    bool? gender,
    String? phone,
    String? direction,
    bool? stateAccount,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithDataUser,
          [
            name,
            lastName,
            gender,
            phone,
            direction,
            stateAccount,
            email,
          ],
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #signUpWithDataUser,
            [
              name,
              lastName,
              gender,
              phone,
              direction,
              stateAccount,
              email,
            ],
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<bool> recoverPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #recoverPassword,
          [email],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.UserModel> getCurrentUser(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [email],
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #getCurrentUser,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<_i2.UserModel> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i7.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveCurrentUser(_i2.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #saveCurrentUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserModel?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.UserModel?>.value(),
      ) as _i4.Future<_i2.UserModel?>);

  @override
  _i4.Future<void> deleteCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteCurrentUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> hasUser() => (super.noSuchMethod(
        Invocation.method(
          #hasUser,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveAuthToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveAuthToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getAuthToken() => (super.noSuchMethod(
        Invocation.method(
          #getAuthToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteAuthToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteAuthToken,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserState(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserState,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<dynamic> getUserState(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getUserState,
          [key],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<void> deleteUserState(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserState,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheUser(_i2.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #cacheUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i2.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> get isSupabaseConnected => (super.noSuchMethod(
        Invocation.getter(#isSupabaseConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
